---
# tasks file for get-asg-of-elb
- name: Get information of all ASGs
  ec2_asg_facts: 
    region: "{{ elb.region }}"
  register: asg_facts

- name: Get the names of the ASG that point to the desired ELB
  set_fact: asg_of_elb="{{ item.auto_scaling_group_name }}"
  with_items: "{{ asg_facts.results }}"
  when: elb.name in item.load_balancer_names
